In [1]:
import json
import numpy as np
import pandas as pd

from sklearn import preprocessing
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

data_file = open('goemotions.json')
data = json.load(data_file)

In [ ]:
#Collecting the words and their frequencies
tokens = []


for lists in data:
    for text in lists[:1]:
        tokens.append(text)
        
cv = CountVectorizer()
        
c_arr = cv.fit(tokens)
print("Vocabulary: ", cv.vocabulary_["that"])
#Prints out the vocabulary, commenting it out because it takes up the whole page on github

In [ ]:
#Printing the size of the vocabulary
print(len(cv.vocabulary_))

In [2]:
#Converting Json array to Numpy Array
npData = np.array(data)
cv = CountVectorizer()
labEncoder = preprocessing.LabelEncoder()
npDataTokens = cv.fit_transform(npData[:,0])
npDataEmotions = labEncoder.fit_transform(npData[:,1])
npDataSentiments = labEncoder.fit_transform(npData[:,2])

In [3]:
#Splitting the data in two halves
train_tokens, test_tokens = train_test_split(npDataTokens, test_size=0.2, train_size=0.8, shuffle=False)
train_emotions, test_emotions = train_test_split(npDataEmotions, test_size=0.2, train_size=0.8, shuffle=False)
train_sentiments, test_sentiments = train_test_split(npDataSentiments, test_size=0.2, train_size=0.8, shuffle=False)

In [4]:
#Emotions 2.3.3 MLP
from sklearn.neural_network import MLPClassifier

In [5]:
emotions_clf = MLPClassifier(max_iter=40)
emotions_clf.fit(train_tokens, train_emotions)

C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(max_iter=40)

In [5]:
sentiments_clf = MLPClassifier()
sentiments_clf.fit(train_tokens, train_sentiments)

MLPClassifier()

In [10]:
#Gridsearch
import joblib

In [8]:
filename1 = "sentiments_Base_MLP_model.sav"
joblib.dump(sentiments_clf,open(filename1,'wb'))

In [11]:
filename2 = "emotions_Base_MLP_model.sav"
joblib.dump(emotions_clf,open(filename2,'wb'))

In [6]:
from sklearn.model_selection import GridSearchCV

In [7]:
mlp_emotions_parameters = {
    'solver': ["adam", "sgd"],
    'hidden_layer_sizes' : [(10,5),(15,10)],
    'activation' : ["sigmoid", "relu", "tanh", "identity"]
}
top_mlp_emotions = GridSearchCV(estimator=MLPClassifier(max_iter=2), param_grid=mlp_emotions_parameters)

In [8]:
top_mlp_emotions.fit(train_tokens, train_emotions)
print("done")

C:\Users\kilne\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 673, in fit
    return self._fit(X, y, incremental=False)
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 357, in _fit
    self._validate_hyperparameters()
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 448, in _validate_hyperparameters
    raise ValueError("The activation '%s' is not supported. Supported "
ValueError: The activation 'sigmoid' is not

C:\Users\kilne\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 673, in fit
    return self._fit(X, y, incremental=False)
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 357, in _fit
    self._validate_hyperparameters()
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 448, in _validate_hyperparameters
    raise ValueError("The activation '%s' is not supported. Supported "
ValueError: The activation 'sigmoid' is not

C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_pe

done


C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(


In [12]:
filename3 = "emotions_Top_MLP_model.sav"
joblib.dump(top_mlp_emotions,open(filename3,'wb'))

In [9]:
mlp_sentiments_parameters = {
    'solver': ["adam", "sgd"],
    'hidden_layer_sizes' : [(10,5),(15,10)],
    'activation' : ["sigmoid", "relu", "tanh", "identity"]
}
top_mlp_sentiments = GridSearchCV(estimator=MLPClassifier(max_iter=2), param_grid=mlp_sentiments_parameters)

In [10]:
top_mlp_sentiments.fit(train_tokens, train_sentiments)
print("done")

C:\Users\kilne\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 673, in fit
    return self._fit(X, y, incremental=False)
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 357, in _fit
    self._validate_hyperparameters()
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 448, in _validate_hyperparameters
    raise ValueError("The activation '%s' is not supported. Supported "
ValueError: The activation 'sigmoid' is not

C:\Users\kilne\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 673, in fit
    return self._fit(X, y, incremental=False)
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 357, in _fit
    self._validate_hyperparameters()
  File "C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 448, in _validate_hyperparameters
    raise ValueError("The activation '%s' is not supported. Supported "
ValueError: The activation 'sigmoid' is not

C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_pe

C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_pe

done


C:\Users\kilne\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(


In [18]:
filename4 = "sentiments_Top_MLP_model.sav"
joblib.dump(top_mlp_sentiments,open(filename4,'wb'))

In [14]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [15]:
emotions_base_mlp_results = emotions_clf.predict(test_tokens)
print(confusion_matrix(test_emotions, emotions_base_mlp_results))

[[ 968   35   10   40   81   12    9   18    8    8   23    6    3   68
     6   85    3   63   99    1  421   35   11   21    6    1   13   35]
 [  32  567   12   36   27    7   12   12    4    9   19    8    2   24
     4    5    1   71   20    0  270    7    1   19    0    6   10   13]
 [  18   11  292  116   16   20   15   17    1   29   43   44    8    8
     5    2    2    3    5    3  300    9    0    7    3    1   14    7]
 [  27   43  136  285   42   26   34   37   15   66   87   58   15   15
    17   14    1    9    8   11  621   20    1   36    2   10   38   15]
 [ 133   32   21   66  370   56   39   34   28   28   75   14    7   31
     8   20    3   46   64   10  946   68   11   51   11   10   30   19]
 [  20   14   11   18   30  178    6    9    7   10   21    3    1    6
     6   13    1   10   16    9  248   42    0    8    8    5   15    1]
 [   7   19   15   22   20    9  199  130    3    9   29   14    1    5
     7    5    2    6    5    5  382    6    2   15    0  

In [16]:
print(classification_report(test_emotions, emotions_base_mlp_results))

              precision    recall  f1-score   support

           0       0.49      0.46      0.48      2089
           1       0.48      0.47      0.48      1198
           2       0.29      0.29      0.29       999
           3       0.20      0.17      0.18      1689
           4       0.25      0.17      0.20      2231
           5       0.24      0.25      0.25       716
           6       0.24      0.21      0.23       934
           7       0.33      0.32      0.33      1181
           8       0.32      0.25      0.28       450
           9       0.17      0.15      0.16       950
          10       0.24      0.21      0.22      1585
          11       0.27      0.23      0.25       622
          12       0.22      0.16      0.18       283
          13       0.21      0.19      0.20       600
          14       0.36      0.38      0.37       364
          15       0.75      0.75      0.75      1409
          16       0.08      0.07      0.07        75
          17       0.30    

In [11]:
sentiments_results = sentiments_clf.predict(test_tokens)
print(confusion_matrix(test_sentiments, sentiments_results))

[[1395  540 1184  677]
 [ 514 4217 1963 1128]
 [ 957 1974 5557 2557]
 [ 489 1045 2186 7981]]


In [12]:
print(classification_report(test_sentiments, sentiments_results))

              precision    recall  f1-score   support

           0       0.42      0.37      0.39      3796
           1       0.54      0.54      0.54      7822
           2       0.51      0.50      0.51     11045
           3       0.65      0.68      0.66     11701

    accuracy                           0.56     34364
   macro avg       0.53      0.52      0.53     34364
weighted avg       0.55      0.56      0.56     34364



In [17]:
top_mlp_emotions_results = top_mlp_emotions.predict(test_tokens)
print(confusion_matrix(test_emotions,top_mlp_emotions_results))

[[1118   29    5    4    0    1    0    2    1    0    4    1    0    1
     3   37    0   32   74    0  740   19    0    0    0    2    1   15]
 [  44  672   13   11    2    0    1    0    2    1   10    2    0    2
     0    4    0   25   19    0  370    7    0    0    0    4    0    9]
 [  21    7  247   50    0    3    2    6    0    2    8   14    0    0
     2    3    0    3    5    0  610    6    0    0    0    4    2    4]
 [  40   54  128   93    0    0    4   13    1    8   25   10    0    0
     5   16    0    4    7    0 1246    6    0    0    0    6   12   11]
 [ 157   30   16   13    0    5    2    9    2    1   20    1    0    4
     4   18    0   18   35    0 1829   35    0    0    0    9   20    3]
 [  30    6    9    6    0   13    1    5    2    4    5    0    0    0
     7   25    0   13   13    0  523   35    0    0    0   11    7    1]
 [   8   21    6    5    0    0   28   32    0    4   14    1    0    0
     4    7    0    1    3    0  783    1    0    0    0  

In [18]:
print(classification_report(test_emotions,top_mlp_emotions_results))

              precision    recall  f1-score   support

           0       0.50      0.54      0.52      2089
           1       0.50      0.56      0.53      1198
           2       0.27      0.25      0.26       999
           3       0.23      0.06      0.09      1689
           4       0.00      0.00      0.00      2231
           5       0.24      0.02      0.03       716
           6       0.33      0.03      0.05       934
           7       0.39      0.11      0.18      1181
           8       0.53      0.14      0.22       450
           9       0.23      0.02      0.03       950
          10       0.17      0.04      0.06      1585
          11       0.47      0.10      0.16       622
          12       0.75      0.01      0.02       283
          13       0.71      0.06      0.11       600
          14       0.54      0.24      0.33       364
          15       0.77      0.77      0.77      1409
          16       0.00      0.00      0.00        75
          17       0.40    

C:\Users\kilne\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kilne\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
top_mlp_sentiments_results = top_mlp_sentiments.predict(test_tokens)

In [15]:
print(confusion_matrix(test_sentiments, top_mlp_sentiments_results))

[[ 822  564 1660  750]
 [ 186 4350 2210 1076]
 [ 432 1934 5969 2710]
 [ 193  963 2092 8453]]


In [16]:
print(classification_report(test_sentiments, top_mlp_sentiments_results))

              precision    recall  f1-score   support

           0       0.50      0.22      0.30      3796
           1       0.56      0.56      0.56      7822
           2       0.50      0.54      0.52     11045
           3       0.65      0.72      0.68     11701

    accuracy                           0.57     34364
   macro avg       0.55      0.51      0.52     34364
weighted avg       0.56      0.57      0.56     34364

